const OUTLINE_ROW_RE = /^\s*(?:[-*]|\d+\.)\s?(.*)$/;
const EMPTY_OUTLINE_ROW_RE = /^\s*(?:[-*]|\d+\.)\s*$/;

/**
 * Convert markdown generated by the old outline-only editor back into
 * plain block prose.
 *
 * A document made only of list items is valid user-authored markdown, so
 * that shape is not enough to identify legacy outline content. The old
 * outline editor also saved its trailing empty "next thought" bullet; use
 * that affordance as the migration signal.
 */
export function unwrapGeneratedOutlineMarkdown(input: string): string {
  const lines = input.replace(/\r\n?/g, "\n").split("\n");
  const nonBlank = lines.filter((line) => line.trim().length > 0);
  if (nonBlank.length === 0) return input;
  if (!nonBlank.every((line) => OUTLINE_ROW_RE.test(line))) return input;
  if (!EMPTY_OUTLINE_ROW_RE.test(nonBlank[nonBlank.length - 1])) return input;

  return nonBlank
    .map((line) => line.replace(OUTLINE_ROW_RE, "$1").trimEnd())
    .filter((line) => line.trim().length > 0)
    .join("\n\n");
}
