import type { Calendar } from "../dates";
import {
  writeDraft,
  writeEmail,
  type MailFolder,
  type VaultWriter,
} from "../emit";
import { FIRMS, FOUNDER, METRICS, RAISE } from "./narrative";

export interface MailIndex {
  /** Message ids present in `inbox/`. Sweep `to_review` cards must reference these. */
  inboxIds: string[];
  /** Enough detail for Sweep cards to describe the message they triaged. */
  byId: Map<string, { from: string; subject: string; date: string; threadId: string }>;
}

interface MessageSeed {
  slug: string;
  folder: MailFolder;
  thread: string;
  from: string;
  fromEmail: string;
  subject: string;
  offset: number;
  time: string;
  read: boolean;
  mentions?: string[];
  links?: string[];
  body: string;
}

/**
 * Every sender is invented and every address uses the reserved `.example` TLD.
 * No message is attributed to a real organization or person — see the note at
 * the top of `narrative.ts`.
 */
const MESSAGES: MessageSeed[] = [
  // ── Investor threads ──────────────────────────────────────────────────────
  {
    slug: "northwind-partner-meeting",
    folder: "inbox",
    thread: "thread-northwind-decision",
    from: "Priya Raman",
    fromEmail: "priya@northwind.example",
    subject: "Partner meeting Thursday — two things to bring",
    offset: -1,
    time: "17:42",
    read: false,
    mentions: ["priya-raman"],
    body: [
      "Confirming Thursday 2pm with the full partnership.",
      "",
      "Two things I'd like in front of us before the discussion:",
      "",
      "1. The retention cut by acquisition source. You mentioned it on our first",
      "call and I've been describing it secondhand ever since, which is not ideal",
      "when I'm the one arguing for this internally.",
      "",
      "2. A direct answer on collaboration. Not a roadmap — I want to understand",
      "what you think the second act is and why the file format doesn't preclude it.",
      "Tomas passed on exactly this and the partnership knows that.",
      "",
      "Happy to see a rough version of either. Polished is not the point.",
      "",
      "Priya",
    ].join("\n"),
  },
  {
    slug: "foundry-references-landed",
    folder: "inbox",
    thread: "thread-foundry-dd",
    from: "Mei Watanabe",
    fromEmail: "mei@foundryline.example",
    subject: "Re: Diligence — references complete",
    offset: -2,
    time: "11:05",
    read: false,
    mentions: ["mei-watanabe"],
    body: [
      "Both reference calls are done and both were strong.",
      "",
      "Worth passing on: Ravi spent most of his call on a data-loss bug you shipped",
      "and how your team handled it. He described the response time and the write-up",
      "in some detail. Daniel's note afterwards was that it told him more than a",
      "clean reference would have.",
      "",
      "Remaining items on our side: the cap table as it stands today, and",
      "confirmation of the current SAFE terms. Nothing controversial.",
      "",
      "Daniel wants to talk terms next week.",
      "",
      "Mei",
    ].join("\n"),
  },
  {
    slug: "daniel-terms-timing",
    folder: "inbox",
    thread: "thread-foundry-dd",
    from: "Daniel Osei",
    fromEmail: "daniel@foundryline.example",
    subject: "Re: Diligence — references complete",
    offset: -1,
    time: "09:20",
    read: true,
    mentions: ["daniel-osei"],
    body: [
      "Adding to Mei's note — I'd like to get to terms quickly.",
      "",
      "One question I want to ask properly rather than in passing: if Northwind",
      "leads, are you looking for us to fill or to co-lead? I have a view but it",
      "depends on your answer, and I'd rather not guess.",
      "",
      "Daniel",
    ].join("\n"),
  },
  {
    slug: "ana-intro-offer",
    folder: "inbox",
    thread: "thread-ana-intros",
    from: "Ana Ferreira",
    fromEmail: "ana@ridgeline.example",
    subject: "Two intros if you want them",
    offset: -6,
    time: "08:15",
    read: true,
    mentions: ["ana-ferreira"],
    body: [
      "Not pushing, but I have two people who'd take a call on your say-so.",
      "",
      "One writes $250-500k and is unusually good on developer tools distribution.",
      "The other is an operator angel who ran a desktop app through exactly the",
      "transition you're about to make.",
      "",
      "Only worth it if the round has room. If Northwind and Foundry Line fill it,",
      "ignore this entirely — a crowded round is worse than a clean one.",
      "",
      "Ana",
    ].join("\n"),
  },
  {
    slug: "ben-security-help",
    folder: "inbox",
    thread: "thread-ben-security",
    from: "Ben Whitfield",
    fromEmail: "ben@bwhitfield.example",
    subject: "Re: security questionnaire",
    offset: -8,
    time: "16:30",
    read: true,
    mentions: ["ben-whitfield"],
    body: [
      "Read your \"when does data leave the machine\" write-up. That's the right",
      "document and it's better than what most Series B companies hand out.",
      "",
      "One suggestion: put the \"what does not happen\" section first. Security",
      "reviewers are scanning for disqualifiers, and \"there is no server\" is the",
      "sentence that ends the review in your favour.",
      "",
      "Ben",
    ].join("\n"),
  },
  {
    slug: "nadia-onboarding-notes",
    folder: "inbox",
    thread: "thread-nadia-onboarding",
    from: "Nadia Haddad",
    fromEmail: "nadia@haddad.example",
    subject: "Onboarding — the screen order matters more than the copy",
    offset: -11,
    time: "13:48",
    read: true,
    mentions: ["nadia-haddad", "casey-kim"],
    body: [
      "Looked at Casey's revised flow.",
      "",
      "The import-first idea is right. But you've kept the vault location question on",
      "screen two, and it still reads as a commitment because the user has no",
      "material yet.",
      "",
      "Move it after the import completes. \"Where should we keep these 340 files\" is",
      "a completely different question from \"where would you like to start a vault\",",
      "and only one of them has an obvious answer.",
      "",
      "Nadia",
    ].join("\n"),
  },
  {
    slug: "lena-yc-answers",
    folder: "inbox",
    thread: "thread-lena-application",
    from: "Lena Fischer",
    fromEmail: "lena@fischer.example",
    subject: "Re: YC answers — read them",
    offset: -4,
    time: "20:10",
    read: false,
    mentions: ["lena-fischer"],
    body: [
      "Read the draft. The \"why did you pick this idea\" answer is the best writing",
      "in the application — leave it exactly as it is.",
      "",
      "\"Why now\" is not an answer, it's the memo with the numbers taken out. Three",
      "claims, none falsifiable. Cut it to one sentence you could be wrong about.",
      "",
      "The competitors answer is close. You're right that Obsidian is the real",
      "threat. You're too polite about why they won't do it.",
      "",
      "Lena",
    ].join("\n"),
  },
  {
    slug: "oskar-checking-in",
    folder: "inbox",
    thread: "thread-oskar",
    from: "Oskar Lindqvist",
    fromEmail: "oskar@northwind.example",
    subject: "How did the partnership go?",
    offset: -14,
    time: "10:00",
    read: true,
    mentions: ["oskar-lindqvist"],
    body: [
      "Heard the partnership meeting ran long. That's the good outcome.",
      "",
      "No agenda here — I made the intro and I'm curious. Let me know if there's",
      "anything useful I can do from inside.",
      "",
      "Oskar",
    ].join("\n"),
  },

  // ── Design partners and product ──────────────────────────────────────────
  {
    slug: "ravi-index-latency",
    folder: "inbox",
    thread: "thread-ravi-perf",
    from: "Ravi Menon",
    fromEmail: "ravi@cartogram.example",
    subject: "Search feels instant now",
    offset: -1,
    time: "14:22",
    read: false,
    mentions: ["ravi-menon"],
    body: [
      "Updated this morning. The pause on first search after launch is gone — I",
      "went looking for it and couldn't reproduce it.",
      "",
      "Vault is at 940 files now. Everything else feels the same, which is the point.",
      "",
      "Separately: is the revision-before-write thing on your list? You mentioned it",
      "after the iCloud fix and I've been thinking about it every time I open the",
      "app on the desktop machine. Not urgent, just want to know it's tracked.",
      "",
      "Ravi",
    ].join("\n"),
  },
  {
    slug: "jonas-security-approved",
    folder: "inbox",
    thread: "thread-ostrich-security",
    from: "Jonas Klein",
    fromEmail: "jonas@ostrich.example",
    subject: "Security review passed — rolling out to 60",
    offset: -3,
    time: "09:30",
    read: false,
    mentions: ["jonas-klein"],
    body: [
      "Our reviewer signed off. The document did it — she said it was the first",
      "vendor answer she'd read that enumerated the network calls instead of",
      "describing a posture.",
      "",
      "We're rolling out to all 60 engineers. I'd like an hour with you before we do",
      "to work through failure modes: what happens when someone's vault is on a",
      "network share, and what our recovery story is if a file gets corrupted.",
      "",
      "Jonas",
    ].join("\n"),
  },
  {
    slug: "sofia-recurring-notes",
    folder: "inbox",
    thread: "thread-sofia-feature",
    from: "Sofia Duarte",
    fromEmail: "sofia@meridian.example",
    subject: "The recurring meeting thing again",
    offset: -9,
    time: "15:12",
    read: true,
    mentions: ["sofia-duarte"],
    body: [
      "Not nagging, just adding evidence.",
      "",
      "I now have eleven separate pages for the same weekly 1:1 with one engineer.",
      "The history is real and completely unreadable — I can't answer \"what did we",
      "agree three months ago\" without opening eleven files.",
      "",
      "I know it's not scheduled. Wanted you to have the concrete version.",
      "",
      "Sofia",
    ].join("\n"),
  },
  {
    slug: "hana-board-view",
    folder: "inbox",
    thread: "thread-hana-databases",
    from: "Hana Sato",
    fromEmail: "hana@cartogram.example",
    subject: "Board view — one more ask, then I'll stop",
    offset: -7,
    time: "11:40",
    read: true,
    mentions: ["hana-sato"],
    body: [
      "Saw the board view is coming. Thank you.",
      "",
      "One more and then I'll genuinely stop: can the group footer show a count as",
      "well as a sum? I mostly want to know how many are in each column, and I keep",
      "counting rows by eye.",
      "",
      "I read your reply about formulas and I think you're right, for what it's worth.",
      "I'd have asked for them and then complained when the files stopped being",
      "readable.",
      "",
      "Hana",
    ].join("\n"),
  },
  {
    slug: "marcus-keyboard",
    folder: "inbox",
    thread: "thread-marcus-keyboard",
    from: "Marcus Bell",
    fromEmail: "marcus@tinderbox.example",
    subject: "Four things that still need the mouse",
    offset: -5,
    time: "22:15",
    read: true,
    mentions: ["marcus-bell"],
    body: [
      "Ran through everything I do in a week and found four actions with no keyboard",
      "path:",
      "",
      "- Reordering tasks (drag only)",
      "- Changing a row's select value from the board view",
      "- Resizing a table column",
      "- Dismissing a calendar event",
      "",
      "The first is the one that actually costs me time.",
      "",
      "Marcus",
    ].join("\n"),
  },
  {
    slug: "havershore-quiet",
    folder: "inbox",
    thread: "thread-havershore",
    from: "Havershore Support",
    fromEmail: "team@havershore.example",
    subject: "Re: How's it going with the trial?",
    offset: -10,
    time: "16:55",
    read: true,
    body: [
      "Thanks for checking in.",
      "",
      "Honest answer: we installed it, everyone made a vault, and then nobody knew",
      "what to put in them. Two weeks later they're all still empty and people have",
      "gone back to the shared docs.",
      "",
      "Not a criticism of the app — it's clearly well built. We just didn't have a",
      "reason to start.",
    ].join("\n"),
  },
  {
    slug: "iris-forum-digest",
    folder: "inbox",
    thread: "thread-iris-community",
    from: "Iris Chen",
    fromEmail: "iris@irischen.example",
    subject: "Forum digest — three recurring questions",
    offset: -12,
    time: "19:20",
    read: true,
    mentions: ["iris-chen"],
    body: [
      "Three things came up more than twice this week:",
      "",
      "1. \"Can I point it at my existing Obsidian folder?\" — asked five times. The",
      "answer is basically yes but nobody can find that out without trying.",
      "2. \"Where are my files actually stored?\" — asked four times, usually by",
      "someone who has been burned before.",
      "3. Sync between two machines. Asked constantly. I've been telling people the",
      "honest version: it works through whatever folder sync you already use, and",
      "conflicts are your problem right now.",
      "",
      "Let me know if that third answer is wrong.",
      "",
      "Iris",
    ].join("\n"),
  },
  {
    slug: "alex-watcher-bug",
    folder: "inbox",
    thread: "thread-alex-watcher",
    from: "Alex Rivera",
    fromEmail: "alex@woodshed.example",
    subject: "Watcher echo on external edits — found it",
    offset: -13,
    time: "18:05",
    read: true,
    mentions: ["alex-rivera"],
    body: [
      "The flicker on external edits was our own fingerprint check racing the",
      "debounce. Fixed, tested, and I added a case for the edit-while-editing path",
      "that we didn't have.",
      "",
      "Worth noting we only found this because Ravi's vault is big enough for the",
      "race to be reliable. On a small vault it basically never fires.",
      "",
      "Alex",
    ].join("\n"),
  },
  {
    slug: "morgan-tag-edges",
    folder: "inbox",
    thread: "thread-morgan-index",
    from: "Morgan Diaz",
    fromEmail: "morgan@woodshed.example",
    subject: "Tag queries now read from edge tables",
    offset: -19,
    time: "12:30",
    read: true,
    mentions: ["morgan-diaz"],
    body: [
      "Tag tables no longer rescan every collection per view. They read the",
      "normalized edges.",
      "",
      "On a 900-file vault that's roughly 40x on the `#rfc` view. On a 50-file vault",
      "you can't measure the difference, which is why we didn't notice for so long.",
      "",
      "Morgan",
    ].join("\n"),
  },
  {
    slug: "casey-onboarding-screens",
    folder: "inbox",
    thread: "thread-casey-onboarding",
    from: "Casey Kim",
    fromEmail: "casey@woodshed.example",
    subject: "Onboarding v3 — three doors",
    offset: -6,
    time: "14:00",
    read: true,
    mentions: ["casey-kim", "nadia-haddad"],
    body: [
      "Third pass, incorporating Nadia's note about screen order.",
      "",
      "Import is now the primary action and the location question happens after we",
      "know what we're storing. \"Start empty\" is still there but it's a text link,",
      "not a button, which I think is the right amount of discouragement.",
      "",
      "Casey",
    ].join("\n"),
  },
  {
    slug: "sam-design-review-agenda",
    folder: "inbox",
    thread: "thread-sam-review",
    from: "Sam Chen",
    fromEmail: "sam@woodshed.example",
    subject: "Design review agenda",
    offset: -3,
    time: "08:45",
    read: true,
    mentions: ["sam-chen"],
    body: [
      "One item: the board view empty-group question.",
      "",
      "Casey wants a visible \"No value\" column, Morgan wants those rows hidden. I",
      "think Casey's right — hiding records is how people lose them, and we are",
      "specifically the product that doesn't lose things.",
      "",
      "Sam",
    ].join("\n"),
  },

  // ── Network, press, personal ─────────────────────────────────────────────
  {
    slug: "theo-launch-timing",
    folder: "inbox",
    thread: "thread-theo-coverage",
    from: "Theo Almeida",
    fromEmail: "theo@almeida.example",
    subject: "Want to cover this when you're ready",
    offset: -15,
    time: "09:10",
    read: true,
    mentions: ["theo-almeida"],
    body: [
      "The angle I'd take is trust, not features — why a local binary is legible in",
      "a way a web app isn't, and what that's worth to people who've been burned.",
      "",
      "No deadline pressure. Tell me when the timing is right and I'll work around",
      "it. I'd rather run it the week something is actually happening.",
      "",
      "Theo",
    ].join("\n"),
  },
  {
    slug: "adeola-papers",
    folder: "inbox",
    thread: "thread-adeola-sync",
    from: "Adeola Bakare",
    fromEmail: "adeola@bakare.example",
    subject: "Two papers, and a warning",
    offset: -20,
    time: "21:30",
    read: true,
    mentions: ["adeola-bakare"],
    body: [
      "Attaching the two OT papers I mentioned. Fair warning: they will make the",
      "shared-vault sketch harder, not easier.",
      "",
      "The thing I'd hold onto is that convergence and coherence are different",
      "properties, and every system that markets the first is quietly hoping you",
      "won't test the second. Your last-write-wins-with-visible-revisions design is",
      "less impressive and more honest.",
      "",
      "Don't let a partner talk you into promising merges.",
      "",
      "Adeola",
    ].join("\n"),
  },
  {
    slug: "grace-candidates",
    folder: "inbox",
    thread: "thread-grace-hiring",
    from: "Grace Lin",
    fromEmail: "grace@lintalent.example",
    subject: "Two Rust people, no pressure",
    offset: -16,
    time: "11:15",
    read: true,
    mentions: ["grace-lin"],
    body: [
      "Holding two candidates who'd both be a fit for the systems role. Neither is",
      "actively looking, which is why they're good.",
      "",
      "I know you're not engaging until the round closes and I think that's right.",
      "Flagging so you know the pipeline exists rather than starting from zero.",
      "",
      "Grace",
    ].join("\n"),
  },
  {
    slug: "jamie-saturday",
    folder: "inbox",
    thread: "thread-jamie",
    from: "Jamie Parker",
    fromEmail: "jamie@jparker.example",
    subject: "Saturday",
    offset: -4,
    time: "19:45",
    read: true,
    mentions: ["jamie-parker"],
    body: [
      "Still on for Saturday? You've cancelled twice and I'm not judging but I am",
      "counting.",
      "",
      "J",
    ].join("\n"),
  },
  {
    slug: "nora-climbing",
    folder: "inbox",
    thread: "thread-nora",
    from: "Nora Whitcomb",
    fromEmail: "nora@whitcomb.example",
    subject: "Tuesday session",
    offset: -2,
    time: "07:30",
    read: true,
    mentions: ["nora-whitcomb"],
    body: [
      "Booked the usual slot. Bring the shoes you keep forgetting.",
      "",
      "Also — do the shoulder thing I sent you. You will not, but I'm saying it.",
      "",
      "N",
    ].join("\n"),
  },
  {
    slug: "devtools-weekly",
    folder: "inbox",
    thread: "thread-newsletter-1",
    from: "Devtools Weekly",
    fromEmail: "hello@devtoolsweekly.example",
    subject: "Issue 212 — the local-first tools people actually use",
    offset: -5,
    time: "06:00",
    read: true,
    links: ["https://devtoolsweekly.example/212"],
    body: [
      "This week: a survey of local-first tools that shipped something in the last",
      "quarter, why the term has stopped meaning anything, and a short interview",
      "about file formats as a trust signal.",
      "",
      "Unsubscribe at any time.",
    ].join("\n"),
  },
  {
    slug: "conference-cfp",
    folder: "inbox",
    thread: "thread-cfp",
    from: "LocalFirst Conf",
    fromEmail: "cfp@localfirstconf.example",
    subject: "CFP closes in a week",
    offset: -9,
    time: "10:20",
    read: false,
    links: ["https://localfirstconf.example/cfp"],
    body: [
      "Reminder that our call for proposals closes next Friday.",
      "",
      "We're particularly interested in talks about what local-first costs you —",
      "the constraints, not the pitch. Twenty-five minutes plus questions.",
    ].join("\n"),
  },
  {
    slug: "invoice-hosting",
    folder: "inbox",
    thread: "thread-invoice-1",
    from: "Cloudpost Billing",
    fromEmail: "billing@cloudpost.example",
    subject: "Invoice #4471 — $88.00",
    offset: -8,
    time: "03:12",
    read: false,
    body: [
      "Your monthly invoice is ready.",
      "",
      "Amount: $88.00",
      "Due: on receipt",
      "",
      "This invoice covers the marketing site and documentation hosting.",
    ].join("\n"),
  },
  {
    slug: "recruiter-spam",
    folder: "inbox",
    thread: "thread-recruiter-spam",
    from: "Talent Reach",
    fromEmail: "outreach@talentreach.example",
    subject: "Exciting VP Engineering opportunity",
    offset: -6,
    time: "13:05",
    read: false,
    body: [
      "Hi there,",
      "",
      "I came across your profile and thought you'd be a great fit for a VP",
      "Engineering role at a fast-growing Series B company.",
      "",
      "Would you be open to a quick 15-minute chat this week?",
    ].join("\n"),
  },
  {
    slug: "quarry-question",
    folder: "inbox",
    thread: "thread-quarry",
    from: "Quarry Labs",
    fromEmail: "eng@quarry.example",
    subject: "Can we point it at a network share?",
    offset: -7,
    time: "15:35",
    read: false,
    body: [
      "We keep our team documentation on an SMB share. Is that a supported vault",
      "location, or are we asking for trouble?",
      "",
      "Happy with \"it'll work but we don't test it\" as an answer, we just want to",
      "know which one it is before eight people rely on it.",
    ].join("\n"),
  },

  // ── Archive ──────────────────────────────────────────────────────────────
  {
    slug: "tomas-pass-email",
    folder: "archive",
    thread: "thread-halyard",
    from: "Tomas Bergström",
    fromEmail: "tomas@halyard.example",
    subject: "Following up on our call",
    offset: -21,
    time: "17:30",
    read: true,
    mentions: ["tomas-bergstrom"],
    body: [
      "As I said on the phone — we're going to pass.",
      "",
      "To put it in writing so you can use it: my concern is the ceiling on",
      "single-player tools, and that the standard answer (\"we'll add teams\") is",
      "structurally hard for you specifically, because a local file format and a",
      "collaborative system pull in opposite directions.",
      "",
      "I could be wrong about that. If you find the version of collaboration that",
      "doesn't compromise the format, I'd want to hear it — genuinely, not as a",
      "courtesy.",
      "",
      "Tomas",
    ].join("\n"),
  },
  {
    slug: "priya-first-call-confirm",
    folder: "archive",
    thread: "thread-northwind-intro",
    from: "Priya Raman",
    fromEmail: "priya@northwind.example",
    subject: "Re: Intro from Oskar",
    offset: -46,
    time: "08:50",
    read: true,
    mentions: ["priya-raman", "oskar-lindqvist"],
    body: [
      "Oskar sent your essay over and I read the changelog afterwards, which is",
      "usually a sign I'm interested.",
      "",
      "Thursday 1pm work?",
      "",
      "Priya",
    ].join("\n"),
  },
  {
    slug: "ravi-icloud-bug",
    folder: "archive",
    thread: "thread-ravi-icloud",
    from: "Ravi Menon",
    fromEmail: "ravi@cartogram.example",
    subject: "I think I lost a file (probably my fault)",
    offset: -49,
    time: "10:15",
    read: true,
    mentions: ["ravi-menon"],
    body: [
      "This is probably something I did, but I renamed an RFC on the laptop and when",
      "I opened the desktop machine it wasn't there. Not in trash either.",
      "",
      "It was a draft so no real loss. Mentioning it in case it's a real thing rather",
      "than me being careless — I did have both machines open at once, which I",
      "assume is asking for trouble.",
      "",
      "Ravi",
    ].join("\n"),
  },
  {
    slug: "mei-diligence-request",
    folder: "archive",
    thread: "thread-foundry-dd",
    from: "Mei Watanabe",
    fromEmail: "mei@foundryline.example",
    subject: "Diligence list",
    offset: -18,
    time: "10:30",
    read: true,
    mentions: ["mei-watanabe"],
    body: [
      "Following our call, the list:",
      "",
      "- Cohort retention by acquisition source, last 6 months",
      "- Paid beta conversion and current MRR",
      "- Two design partner references",
      "- Cap table and current SAFE terms",
      "",
      "No rush on any of it, but the references are the long pole.",
      "",
      "Mei",
    ].join("\n"),
  },
  {
    slug: "jonas-questionnaire",
    folder: "archive",
    thread: "thread-ostrich-security",
    from: "Jonas Klein",
    fromEmail: "jonas@ostrich.example",
    subject: "Vendor security review — what we need",
    offset: -29,
    time: "09:00",
    read: true,
    mentions: ["jonas-klein"],
    body: [
      "Before we can go past five seats I need to put you through our vendor review.",
      "",
      "I'm not going to send you the 300-question spreadsheet. The question our",
      "reviewer actually cares about is: under what circumstances does any content",
      "from a user's vault leave their machine? An enumerable list, not a posture",
      "statement.",
      "",
      "If the answer is short, say so and we'll move fast.",
      "",
      "Jonas",
    ].join("\n"),
  },
  {
    slug: "lena-should-you-raise",
    folder: "archive",
    thread: "thread-lena-raise",
    from: "Lena Fischer",
    fromEmail: "lena@fischer.example",
    subject: "Re: should I raise",
    offset: -56,
    time: "07:20",
    read: true,
    mentions: ["lena-fischer"],
    body: [
      "Short version: yes, but not with the pitch you just described to me.",
      "",
      "You led with seven surfaces in one app. That's a feature list and it makes you",
      "sound like every other productivity tool that raised and died.",
      "",
      "Lead with the files. You are not selling a note app, you are selling the claim",
      "that the files outlive the company. Everything else is downstream of whether",
      "they believe that.",
      "",
      "Call Thursday if useful.",
      "",
      "Lena",
    ].join("\n"),
  },
  {
    slug: "marcus-first-payment",
    folder: "archive",
    thread: "thread-marcus-paid",
    from: "Marcus Bell",
    fromEmail: "marcus@tinderbox.example",
    subject: "Took my money",
    offset: -30,
    time: "12:00",
    read: true,
    mentions: ["marcus-bell"],
    body: [
      "Saw the paid beta go up and subscribed before you announced it.",
      "",
      "For the record: I'm not paying because of a feature. I'm paying because the",
      "files are mine and I believe you'll still be around, and those are the same",
      "sentence.",
      "",
      "Marcus",
    ].join("\n"),
  },
  {
    slug: "old-newsletter",
    folder: "archive",
    thread: "thread-newsletter-0",
    from: "Devtools Weekly",
    fromEmail: "hello@devtoolsweekly.example",
    subject: "Issue 211 — desktop apps are back",
    offset: -12,
    time: "06:00",
    read: true,
    links: ["https://devtoolsweekly.example/211"],
    body: "This week: why native desktop shipped more interesting software than the web did this quarter.",
  },

  // ── Sent ─────────────────────────────────────────────────────────────────
  {
    slug: "sent-monthly-update",
    folder: "sent",
    thread: "thread-update-monthly",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Woodshed — monthly update",
    offset: -5,
    time: "17:00",
    read: true,
    body: [
      "Monthly update. Same three metrics as always.",
      "",
      "**Numbers**",
      `- WAU: ${METRICS.wauCurrent} (from ${METRICS.wauEightWeeksAgo} eight weeks ago)`,
      `- Week-4 retention: ${METRICS.weekFourRetention}%`,
      `- MRR: $${(METRICS.mrr / 1000).toFixed(1)}k`,
      "",
      "**Shipped**",
      "- Search index warm-up — first-query latency on large vaults is gone",
      "- Tag queries now read normalized edges instead of rescanning collections",
      "- iCloud direct-write fallback (fixes a data-loss bug on renames)",
      "",
      "**Learned**",
      "The retention number was hiding the actual finding. Users who arrive with",
      "existing material stay; users who start from an empty vault leave. That",
      "changed the onboarding roadmap rather than the marketing.",
      "",
      "**Ask**",
      "Nothing this month.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-jonas-security-answer",
    folder: "sent",
    thread: "thread-ostrich-security",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Re: Vendor security review — what we need",
    offset: -27,
    time: "16:20",
    read: true,
    body: [
      "The answer is short, so here it is in full.",
      "",
      "Content leaves the machine in exactly five cases, all user-initiated:",
      "",
      "1. Mail — IMAP/SMTP to the provider you configured, on sync or send",
      "2. Calendar — HTTPS GET of the read-only iCal URL you supplied",
      "3. Saved links — one HTTPS fetch of a URL you explicitly saved",
      "4. Remote images in HTML mail — through a bounded local cache; sender HTML",
      "   never fetches anything directly",
      "5. Agent — requests to the endpoint you configured, after an explicit send",
      "",
      "What does not happen: no account system, no telemetry, no crash reporting,",
      "no Woodshed-operated backend of any kind. There is no server for vault",
      "contents to be sent to.",
      "",
      "Credentials live in the OS credential store, never in the vault or config.",
      "",
      "Happy to walk your reviewer through any of it.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-ravi-icloud-reply",
    folder: "sent",
    thread: "thread-ravi-icloud",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Re: I think I lost a file (probably my fault)",
    offset: -49,
    time: "11:40",
    read: true,
    body: [
      "It's not your fault and it's a real bug. Thank you for reporting it even",
      "though you thought it was.",
      "",
      "Renames across the iCloud sync boundary aren't reliably atomic and we were",
      "assuming they were. Alex is on it today. I'll write up what we change and",
      "send it to you rather than just telling you it's fixed.",
      "",
      "The part that bothers me most is that you sat on it for two days because you",
      "assumed you'd done something wrong. That's a failure on our side — this class",
      "of bug should be loud.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-priya-followup",
    folder: "sent",
    thread: "thread-northwind-decision",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Re: Partner meeting Thursday — two things to bring",
    offset: -1,
    time: "21:05",
    read: true,
    body: [
      "Both make sense. Retention cut will be with you Wednesday — it exists, I've",
      "just been describing it badly rather than sending it.",
      "",
      "On collaboration: I'd rather give you the real answer than a roadmap slide.",
      "Short version is shared vaults between people who already trust each other,",
      "not real-time multiplayer, with conflicts surfaced honestly rather than merged",
      "automatically. I'll write it up properly before Thursday.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-havershore-reply",
    folder: "sent",
    thread: "thread-havershore",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Re: How's it going with the trial?",
    offset: -10,
    time: "18:20",
    read: true,
    body: [
      "That's genuinely useful and not a criticism I'm going to argue with.",
      "",
      "You're the third team to describe exactly this. An empty vault is a chore, and",
      "we've been treating it as a blank canvas. We're rebuilding onboarding around",
      "importing what you already have instead.",
      "",
      "If you'd be willing to try again once that ships, I'll set it up with you",
      "directly. If not, that's fair too.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-lena-thanks",
    folder: "sent",
    thread: "thread-lena-application",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Re: YC answers — read them",
    offset: -4,
    time: "22:30",
    read: true,
    body: [
      "You're right about \"why now\". It's three claims and none of them could be",
      "wrong, which means none of them are saying anything.",
      "",
      "Cutting it to one sentence tomorrow morning.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-alex-runway",
    folder: "sent",
    thread: "thread-alex-runway",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "The runway number, properly",
    offset: -31,
    time: "20:15",
    read: true,
    body: [
      "You asked in our 1:1 and I gave you a vague answer, which wasn't fair.",
      "",
      "Seven months at current burn without the round. Not nine, not \"into next",
      "year\".",
      "",
      `${RAISE.committed} is committed, so the round happening isn't the question —`,
      "a lead changes the terms and the timeline, not whether we survive. But I'd",
      "rather you had the actual number.",
      "",
      "Dana",
    ].join("\n"),
  },
  {
    slug: "sent-theo-timing",
    folder: "sent",
    thread: "thread-theo-coverage",
    from: FOUNDER.name,
    fromEmail: FOUNDER.email,
    subject: "Re: Want to cover this when you're ready",
    offset: -14,
    time: "12:45",
    read: true,
    body: [
      "Trust rather than features is the right angle and I'd rather you wrote it than",
      "anyone else.",
      "",
      "Can we talk in a couple of weeks? There's something happening that would make",
      "the timing better, and I'd rather not be vague about it on email for much",
      "longer.",
      "",
      "Dana",
    ].join("\n"),
  },
];

interface DraftSeed {
  id: string;
  kind: "new" | "reply";
  to: string[];
  subject: string;
  offset: number;
  time: string;
  threadId?: string;
  body: string;
}

const DRAFTS: DraftSeed[] = [
  {
    id: "draft-collaboration-answer",
    kind: "reply",
    to: ["priya@northwind.example"],
    subject: "Re: Partner meeting Thursday — two things to bring",
    offset: 0,
    time: "15:10",
    threadId: "thread-northwind-decision",
    body: [
      "Priya — the collaboration answer, written down properly rather than",
      "improvised.",
      "",
      "It is not real-time multiplayer and it never will be. A shared vault is a",
      "folder two to six people each hold a complete copy of, synced over a transport",
      "they already trust. No server of record, so the privacy claim survives intact.",
      "",
      "Conflicts become visible and frequent instead of rare. We don't merge prose",
      "automatically — every superseded version is kept as a visible revision and the",
      "user resolves it. Less impressive than a CRDT story, and it's the version that",
      "doesn't quietly corrupt someone's writing.",
      "",
      "The honest part: this is a sketch, not a plan, and it isn't scheduled. Single",
      "player isn't finished, and shipping a mediocre collaboration story to answer a",
      "market objection is how this product loses what makes it worth buying.",
      "",
      "[TODO: is this too honest for a partner meeting? Ask Lena.]",
    ].join("\n"),
  },
  {
    id: "draft-iris-thanks",
    kind: "new",
    to: ["iris@irischen.example"],
    subject: "You should be getting paid for this",
    offset: -1,
    time: "23:40",
    body: [
      "Iris —",
      "",
      "You've been doing community management for us for four months and we have not",
      "paid you a penny, and every time I think about it I file it under \"after the",
      "round\", which is now four months of after.",
      "",
      "[TODO: figure out what the actual offer is before sending this. A retainer? A",
      "role? Don't send an apology with no proposal attached.]",
    ].join("\n"),
  },
  {
    id: "draft-quarry-network-share",
    kind: "reply",
    to: ["eng@quarry.example"],
    subject: "Re: Can we point it at a network share?",
    offset: -6,
    time: "16:00",
    threadId: "thread-quarry",
    body: [
      "Short answer: it will probably work and we don't test it, so I'd rather tell",
      "you that than have you find out with eight people depending on it.",
      "",
      "The specific risk is that our atomic write path relies on rename being atomic,",
      "and over SMB that guarantee is thinner than on a local disk. We already have a",
      "direct-write fallback for iCloud for exactly this reason.",
      "",
      "[TODO: check with Alex whether the iCloud detection can be generalised to any",
      "non-local mount before promising anything.]",
    ].join("\n"),
  },
];

/** Gmail-ish message id. Deterministic so re-running produces identical files. */
function messageId(slug: string): string {
  let hash = 0;
  for (let i = 0; i < slug.length; i += 1) {
    hash = (hash * 31 + slug.charCodeAt(i)) >>> 0;
  }
  return `CA+${hash.toString(36)}${slug.length.toString(36)}@mail.example`;
}

export function buildMail(w: VaultWriter, cal: Calendar): MailIndex {
  const inboxIds: string[] = [];
  const byId = new Map<
    string,
    { from: string; subject: string; date: string; threadId: string }
  >();

  for (const message of MESSAGES) {
    const id = messageId(message.slug);
    const date = cal.at(message.offset, message.time);
    // Read state is derived from labels (mail.rs:16). `archived` marks the
    // folder move so a re-sync doesn't pull the message back into the inbox.
    const labels = [message.read ? "read" : "unread"];
    if (message.folder === "archive") labels.push("archived");

    writeEmail(w, message.folder, {
      id,
      slug: message.slug,
      threadId: message.thread,
      inbox: FOUNDER.inbox,
      from: message.from,
      fromEmail: message.fromEmail,
      subject: message.subject,
      date,
      read: message.read,
      labels,
      mentions: message.mentions ?? [],
      links: message.links ?? [],
      body: message.body,
    });

    if (message.folder === "inbox") inboxIds.push(id);
    byId.set(id, {
      from: message.from,
      subject: message.subject,
      date,
      threadId: message.thread,
    });
  }

  for (const draft of DRAFTS) {
    writeDraft(w, {
      id: draft.id,
      created: cal.at(draft.offset, draft.time),
      kind: draft.kind,
      fromInbox: FOUNDER.inbox,
      to: draft.to,
      subject: draft.subject,
      threadId: draft.threadId,
      body: draft.body,
    });
  }

  return { inboxIds, byId };
}

/** Message id for a seeded slug — lets Sweep cards bind to real inbox files. */
export function inboxMessageId(slug: string): string {
  const found = MESSAGES.find(
    (message) => message.slug === slug && message.folder === "inbox",
  );
  if (!found) throw new Error(`no inbox message with slug "${slug}"`);
  return messageId(slug);
}
