import type { Calendar } from "../dates";
import { writeNote, type VaultWriter } from "../emit";
import { AREA, COMPANIES, FIRMS, METRICS, RAISE, TAGS } from "./narrative";

interface NoteSeed {
  id: string;
  title: string;
  area: string;
  /** Days before demo day the note was written. */
  offset: number;
  time: string;
  tags: string[];
  favorite?: boolean;
  body: string;
}

const NOTES: NoteSeed[] = [
  // ── The raise ─────────────────────────────────────────────────────────────
  {
    id: "seed-investor-memo",
    title: "Seed investor memo",
    area: AREA.fundraise,
    offset: -54,
    time: "07:40",
    tags: [TAGS.fundraise, TAGS.positioning],
    favorite: true,
    body: [
      "## The claim",
      "",
      "Every knowledge tool you have ever paid for will eventually shut down, get",
      "acquired, or change in a way you did not ask for. When that happens, your",
      "notes go with it. Woodshed is a bet that a meaningful number of people have",
      "learned this the hard way and will not do it again.",
      "",
      "The product is a native desktop application over a folder of Markdown files.",
      "Not a sync layer, not an export button — the folder *is* the database. If",
      "Woodshed disappears tomorrow, the user loses a nice interface and keeps every",
      "record.",
      "",
      "## Why now",
      "",
      "Three things changed at once.",
      "",
      "1. A generation of knowledge workers has now personally lost data to a tool",
      "   shutdown. That was theoretical in 2015. It is a lived grievance in 2026.",
      "2. Local models made \"your data never leaves the machine\" a feature people",
      "   can actually evaluate rather than a slogan.",
      "3. Desktop shells got good enough that a native app is a weekend of setup",
      "   rather than a team of specialists.",
      "",
      "## Traction",
      "",
      `- ${METRICS.wauCurrent} weekly active users, up from ${METRICS.wauEightWeeksAgo}`,
      "  eight weeks ago",
      `- ${METRICS.vaultsCreated} vaults created`,
      `- ${METRICS.designPartners} design partners, including two teams above 40`,
      "  engineers",
      `- ${METRICS.weekFourRetention}% week-four retention on the desktop app`,
      `- $${(METRICS.mrr / 1000).toFixed(1)}k MRR from an unadvertised paid beta`,
      "",
      "The retention number is the one that matters and the one I am least",
      "comfortable with. It is good for a productivity tool and not yet good enough",
      "to claim the habit is formed. See [[Retention — what the number actually says]].",
      "",
      "## What the money is for",
      "",
      `Raising ${RAISE.target} on a ${RAISE.cap} cap ${RAISE.instrument}.`,
      "Eighteen months of runway for four people. Two engineering hires, one design",
      "contractor converting to full-time, and enough room to be wrong twice about",
      "the collaboration story without it being fatal.",
      "",
      "## The obvious objection",
      "",
      "Single-player tools do not reach venture scale. [[Tomas Bergström]] passed on",
      "exactly this and he is not wrong about the base rate.",
      "",
      "The answer is not \"we will add collaboration later\" — that is the answer that",
      "kills the product. The answer is that the wedge is single-player and the",
      "expansion is *shared vaults between people who already trust each other*,",
      "which is a different shape from real-time multiplayer and does not require",
      "abandoning the file format.",
      "",
      "Whether that is a big enough second act is the honest open question of this",
      "raise. I would rather have it asked directly than have it discovered in",
      "diligence.",
    ].join("\n"),
  },
  {
    id: "yc-application-draft",
    title: "YC W27 application — draft answers",
    area: AREA.fundraise,
    offset: -9,
    time: "21:10",
    tags: [TAGS.fundraise],
    favorite: true,
    body: [
      "Draft answers. Due Friday. Keep every answer under the limit and cut anything",
      "that sounds like a pitch deck.",
      "",
      "## What is your company going to make?",
      "",
      "A desktop knowledge manager whose database is a folder of Markdown files on",
      "the user's own disk. Calendar, tasks, notes, mail, saved links, a personal",
      "CRM, and lightweight databases — one graph, one folder, no account.",
      "",
      "## Why did you pick this idea to work on?",
      "",
      "I lost eight years of notes when a tool I paid for shut down and its export",
      "produced files that nothing could open. I rebuilt what I could from memory",
      "and then built the thing I wished had existed. I have used it daily for",
      "fourteen months; the vault I am writing this application in is the product.",
      "",
      "## What is new about what you are making?",
      "",
      "Most \"local-first\" tools mean an app with a sync engine and a local cache.",
      "The database is still theirs; you are just allowed a copy. Here the Markdown",
      "files are canonical and everything else — the search index, the calendar",
      "cache, the link graph — is derived and disposable. You can delete every piece",
      "of app state and lose nothing.",
      "",
      "That constraint is unusual because it is expensive. It rules out the schema",
      "flexibility a real database gives you, and it means every feature has to be",
      "expressible as files a human could read. That is also why it is defensible:",
      "a competitor with a cloud backend cannot adopt it without giving up their",
      "business model.",
      "",
      "## Who are your competitors and who is most likely to become one?",
      "",
      "Obsidian owns the file-over-app position for notes and is genuinely good.",
      "Notion owns structured collaborative docs. Neither is trying to be the",
      "surface where your calendar, mail, and tasks live in the same graph as your",
      "notes, because doing that well requires being a native app and neither wants",
      "to be one.",
      "",
      "The most likely new competitor is Obsidian itself, if they decide to ship",
      "first-party calendar and mail rather than leave it to plugins.",
      "",
      "## How far along are you?",
      "",
      `Shipping to ${METRICS.wauCurrent} weekly actives and`,
      `${METRICS.designPartners} design partners. Paid beta at`,
      `$${(METRICS.mrr / 1000).toFixed(1)}k MRR that we have never advertised.`,
      "",
      "## TODO before submitting",
      "",
      "- [ ] Cut the \"why now\" answer by a third, it reads like the memo",
      "- [ ] Record the demo video — one take, no slides, open a real vault",
      "- [ ] Have [[Lena Fischer]] read the competitors answer",
    ].join("\n"),
  },
  {
    id: "spc-application-notes",
    title: "South Park Commons — what to lead with",
    area: AREA.fundraise,
    offset: -7,
    time: "08:20",
    tags: [TAGS.fundraise, TAGS.positioning],
    body: [
      "SPC is a different audience from YC and the application should not be a copy.",
      "",
      "YC wants to know if this becomes big. SPC wants to know if the problem is",
      "genuinely unsolved and whether I am the person who is going to keep pulling on",
      "it. That favours the technical argument over the market argument.",
      "",
      "So lead with the constraint, not the traction:",
      "",
      "> The files are canonical and everything else is disposable. Here is what that",
      "> rules out, here is what it buys, and here is the part I have not solved.",
      "",
      "The unsolved part is honest and worth saying out loud: multi-device editing",
      "without a server, without CRDTs, and without lying to the user about conflict",
      "resolution. [[Adeola Bakare]] thinks the answer is visible revisions plus",
      "last-write-wins rather than pretending merges are automatic. I agree and it is",
      "not fully built.",
      "",
      "Dinner is on demo day. Bring the laptop, not slides.",
    ].join("\n"),
  },
  {
    id: "retention-what-the-number-says",
    title: "Retention — what the number actually says",
    area: AREA.fundraise,
    offset: -16,
    time: "16:45",
    tags: [TAGS.fundraise, TAGS.dd],
    body: [
      `Week-four retention is ${METRICS.weekFourRetention}%. Every investor asks about`,
      "it and I have been answering slightly differently each time, which is a sign I",
      "have not thought it through properly.",
      "",
      "The honest breakdown:",
      "",
      "- People who connected a calendar or mailbox in week one retain at roughly",
      "  twice the rate of people who only wrote notes.",
      "- People who imported an existing folder of Markdown retain best of all.",
      "- People who started from an empty vault mostly churn, and I think that is a",
      "  real signal rather than a funnel problem. An empty vault is a chore.",
      "",
      "So the number is not \"38% of users form a habit\". It is closer to \"users who",
      "arrive with existing material form a habit; users who do not, do not\".",
      "",
      "That is a better story than the raw number and it points at an actual product",
      "decision: onboarding should be about getting material *in*, not about",
      "explaining what a vault is. See [[RFC — onboarding starts with import]].",
      "",
      "Say this version to [[Priya Raman]] on Thursday. It is more useful than the",
      "aggregate and she will find it herself anyway.",
    ].join("\n"),
  },
  {
    id: "halyard-pass-postmortem",
    title: "Halyard passed — postmortem",
    area: AREA.fundraise,
    offset: -21,
    time: "18:30",
    tags: [TAGS.fundraise],
    body: [
      `${FIRMS.halyard} passed after the second call. [[Tomas Bergström]] was direct`,
      "about why, which is worth more than a polite maybe.",
      "",
      "His reasoning: single-player productivity tools have a ceiling, the expansion",
      "path is always \"add teams\", and adding teams to a local-first file format is",
      "either impossible or turns you into a normal SaaS company with extra steps.",
      "He did not want to underwrite finding out which.",
      "",
      "What I got wrong in the meeting: I answered the collaboration question",
      "defensively, as though it were an attack on the thesis. It is the single",
      "sharpest question about this business and I should have had a real answer",
      "rather than a reframe.",
      "",
      "What I would say now: shared vaults between people who already trust each",
      "other — a team of four, a couple, a research group — is a different product",
      "from real-time multiplayer, does not require a server of record, and is worth",
      "roughly ten times the current price. That is a claim I can defend.",
      "",
      "Nothing to fix in the product. Something to fix in how I answer.",
    ].join("\n"),
  },

  // ── User interviews ───────────────────────────────────────────────────────
  {
    id: "interview-ravi-menon",
    title: "User interview — Ravi Menon, Cartogram",
    area: AREA.growth,
    offset: -38,
    time: "11:30",
    tags: [TAGS.userInterview, TAGS.localFirst],
    body: [
      `[[Ravi Menon]] · Staff Engineer · ${COMPANIES.cartogram} · 45 min`,
      "",
      "## How he uses it",
      "",
      "RFC drafts and incident notes. Roughly 900 files, which is more than anything",
      "we test against. Keeps the vault in iCloud so it follows him between a laptop",
      "and a desktop.",
      "",
      "## What he said",
      "",
      "> The reason I trust this is that I can `grep` it. That sounds petty but it is",
      "> the whole thing. I have been burned by tools where the export is technically",
      "> complete and practically useless.",
      "",
      "On search: expects it to be instant at his vault size and it currently is not,",
      "quite. Noticeable pause on the first query after launch.",
      "",
      "On the iCloud bug: found a case where a rename across the sync boundary lost",
      "the file. Already fixed with the direct-write fallback, but his reaction was",
      "the useful part — he did not report it for two days because he assumed he had",
      "done something wrong. Data-loss bugs need to be loud.",
      "",
      "## What to do",
      "",
      "- Warm the index at launch rather than on first query",
      "- Surface write failures in the UI instead of only the log",
    ].join("\n"),
  },
  {
    id: "interview-sofia-duarte",
    title: "User interview — Sofia Duarte, Meridian Labs",
    area: AREA.growth,
    offset: -33,
    time: "14:00",
    tags: [TAGS.userInterview],
    body: [
      `[[Sofia Duarte]] · Engineering Manager · ${COMPANIES.meridian} · 40 min`,
      "",
      "Runs twelve people. Every 1:1 note, every performance-review draft, and her",
      "own weekly planning live in the vault.",
      "",
      "## The thing she does that we did not design for",
      "",
      "She opens a person's page before every 1:1 and reads the backlinks — every",
      "meeting note, task, and journal entry that mentions them, in one place. She",
      "described this as \"the only reason I look competent in 1:1s\".",
      "",
      "We built backlinks as a graph feature. She uses them as a CRM. That is the",
      "more valuable framing and the People surface should lean into it.",
      "",
      "## What she wants",
      "",
      "Recurring meetings to thread their notes across occurrences — right now each",
      "occurrence is a separate page and the history is scattered. Reasonable, not",
      "scheduled.",
      "",
      "## Quote worth keeping",
      "",
      "> I do not want my team's performance conversations sitting on someone else's",
      "> server. That is not paranoia, that is just what the file being local means",
      "> to me.",
    ].join("\n"),
  },
  {
    id: "interview-jonas-klein",
    title: "User interview — Jonas Klein, Ostrich Systems",
    area: AREA.growth,
    offset: -29,
    time: "10:00",
    tags: [TAGS.userInterview, TAGS.dd],
    body: [
      `[[Jonas Klein]] · CTO · ${COMPANIES.ostrich} · 35 min`,
      "",
      "Regulated market, 60 people, and a genuine procurement process. The most",
      "\"enterprise\" conversation we have had and useful precisely because it does not",
      "fit the ICP.",
      "",
      "## What he needs",
      "",
      "A written answer to one question: under what circumstances does any vault",
      "content leave the machine? Not a marketing claim — an enumerable list he can",
      "hand to his security reviewer.",
      "",
      "The answer exists and is short: configured integrations when the user invokes",
      "them, remote images in HTML mail through a bounded cache, and nothing else.",
      "But it lived in my head and in the code, not in a document.",
      "",
      "## What this told me",
      "",
      "The security model is a *sales asset* and we have been treating it as an",
      "implementation detail. Writing it down properly unblocked a 60-person",
      "deployment. That is a better ROI than most features.",
      "",
      "Follow-up: [[Ben Whitfield]] offered to help with the questionnaire format.",
    ].join("\n"),
  },
  {
    id: "interview-marcus-bell",
    title: "User interview — Marcus Bell, Tinderbox",
    area: AREA.growth,
    offset: -24,
    time: "16:00",
    tags: [TAGS.userInterview, TAGS.positioning],
    body: [
      `[[Marcus Bell]] · Founder · ${COMPANIES.tinderbox} · 30 min`,
      "",
      "Textbook ICP. Paid the day the beta opened without being asked.",
      "",
      "## Why he bought",
      "",
      "> I pay for tools the way I pay for a good chair. It is not an expense, it is",
      "> the thing I sit in for nine hours. The question is never price, it is whether",
      "> you are still going to be here in three years — and the file format is your",
      "> answer to that.",
      "",
      "That is the sales pitch, said better than I say it.",
      "",
      "## Where he pushes",
      "",
      "Wants the command palette to do everything, and is annoyed by any action that",
      "requires the mouse. Keyboard-completeness is table stakes for this buyer and",
      "we are maybe 80% there.",
      "",
      "## Churn risk",
      "",
      "Low, but the reason matters: he would leave instantly if the app started",
      "feeling generic. His words. Every feature that makes the product more like",
      "everything else costs us this customer.",
    ].join("\n"),
  },
  {
    id: "interview-hana-sato",
    title: "User interview — Hana Sato, Cartogram",
    area: AREA.growth,
    offset: -19,
    time: "13:15",
    tags: [TAGS.userInterview],
    body: [
      `[[Hana Sato]] · Principal PM · ${COMPANIES.cartogram} · 30 min`,
      "",
      "Uses tag tables the way most people use spreadsheets — filters a `#rfc` view",
      "by area and status and works out of it all week.",
      "",
      "## The tension she exposed",
      "",
      "She wants grouped board views with per-column rollups. Every request she makes",
      "is individually reasonable and collectively turns Databases into Airtable.",
      "",
      "Holding the line: Databases is a *view* over Markdown records. The moment a",
      "cell value can only be understood by the app, the file-over-app promise is",
      "gone and the whole thesis with it.",
      "",
      "Shipping the grouped board view. Not shipping formulas that reference other",
      "rows.",
      "",
      "## Worth noting",
      "",
      "She had not realised tag tables and custom tables were different things. That",
      "is a naming failure on our side, not a comprehension failure on hers.",
    ].join("\n"),
  },
  {
    id: "interview-iris-chen",
    title: "User interview — Iris Chen, community",
    area: AREA.growth,
    offset: -13,
    time: "09:45",
    tags: [TAGS.userInterview, TAGS.positioning],
    body: [
      "[[Iris Chen]] · power user · 30 min",
      "",
      "Found us through the file-over-app essay. Has answered more support questions",
      "in the forum than the team has, unpaid, for four months.",
      "",
      "## What she said about why people show up",
      "",
      "> Nobody arrives wanting a knowledge manager. They arrive angry at a tool that",
      "> let them down. You are not competing on features, you are competing on",
      "> whether someone believes you.",
      "",
      "## What she said about why people leave",
      "",
      "The empty vault. She watched three people in the forum quit in week one",
      "because they did not know what to put in it. Matches",
      "[[Retention — what the number actually says]] exactly, from a completely",
      "different direction.",
      "",
      "## Action",
      "",
      "She should be compensated. She is doing community management for free and I",
      "have been letting it happen because it is convenient. Fix after the round.",
    ].join("\n"),
  },

  // ── Engineering RFCs ──────────────────────────────────────────────────────
  {
    id: "rfc-onboarding-starts-with-import",
    title: "RFC — onboarding starts with import",
    area: AREA.product,
    offset: -12,
    time: "11:00",
    tags: [TAGS.rfc],
    body: [
      "**Status:** draft · **Author:** me · **Reviewers:** [[Casey Kim]], [[Sam Chen]]",
      "",
      "## Problem",
      "",
      "Onboarding asks the user to choose a vault location before they understand",
      "what a vault is, then drops them into an empty app. Two independent sources",
      "say this is where users are lost: [[Retention — what the number actually says]]",
      "and [[User interview — Iris Chen, community]].",
      "",
      "## Proposal",
      "",
      "Invert it. First screen offers three doors:",
      "",
      "1. **Import a folder** — point at existing Markdown, we index it in place",
      "2. **Connect a calendar or mailbox** — the vault fills with real material",
      "   immediately",
      "3. **Start empty** — still available, no longer the default path",
      "",
      "The vault location question moves *after* the user has material worth storing,",
      "where it reads as a reasonable question instead of a commitment.",
      "",
      "## Non-goals",
      "",
      "Not building an importer for proprietary formats. Markdown folders only. The",
      "moment we write a Notion importer we own its schema drift forever.",
      "",
      "## Open question",
      "",
      "Import-in-place means the user's folder is not laid out the way we expect —",
      "no `tasks/`, no `cadence/`. Do we migrate their structure, or teach the app to",
      "read an arbitrary tree? [[Alex Rivera]] thinks the second, and is probably",
      "right, and it is considerably more work.",
    ].join("\n"),
  },
  {
    id: "rfc-index-warmup",
    title: "RFC — warm the search index at launch",
    area: AREA.product,
    offset: -26,
    time: "15:20",
    tags: [TAGS.rfc],
    body: [
      "**Status:** accepted · **Author:** [[Morgan Diaz]]",
      "",
      "## Problem",
      "",
      "First search after launch has a visible pause on large vaults — [[Ravi Menon]]",
      "at ~900 files sees a few hundred milliseconds, which is exactly the kind of",
      "detail this audience notices and holds against you.",
      "",
      "Cause is not the query. It is opening the SQLite connection and letting FTS5",
      "fault its structures in on first use.",
      "",
      "## Proposal",
      "",
      "Open the index connection and run one throwaway query during startup, off the",
      "UI thread, after the window is painted. Cost is a few milliseconds of",
      "background work on a thread nobody is waiting for.",
      "",
      "## Why not eager full rebuild",
      "",
      "Considered and rejected. Rebuilding at launch would make cold start scale with",
      "vault size, which is the opposite of what we want. The index is already",
      "durable across restarts; it only needs waking, not rebuilding.",
      "",
      "## Result",
      "",
      "Shipped. First-query latency on Ravi's vault went from noticeable to not.",
    ].join("\n"),
  },
  {
    id: "rfc-icloud-write-path",
    title: "RFC — iCloud direct-write fallback",
    area: AREA.product,
    offset: -47,
    time: "10:30",
    tags: [TAGS.rfc, TAGS.localFirst],
    body: [
      "**Status:** shipped · **Author:** [[Alex Rivera]]",
      "",
      "## Problem",
      "",
      "Atomic writes work by writing a temp file and renaming it over the target.",
      "Across an iCloud sync boundary the rename is not reliably atomic and, in the",
      "case [[Ravi Menon]] hit, the file was lost entirely.",
      "",
      "A knowledge tool that loses a file has no second chance with that user. This",
      "was the highest-severity bug we have shipped.",
      "",
      "## Proposal",
      "",
      "Detect iCloud-backed paths and fall back to a direct write with fsync for",
      "those, keeping rename-based atomicity everywhere else. The exception is",
      "contained inside the vault helpers so no calling code has to know.",
      "",
      "## Trade-off, stated plainly",
      "",
      "Direct write has a real crash window where the file is partially written. That",
      "is strictly worse than atomic rename — but it is better than a rename that",
      "silently drops the file, which is what we had.",
      "",
      "## Follow-up",
      "",
      "Write a revision to `.woodshed/` before the direct write, so a crash mid-write",
      "leaves a recoverable copy. Not done yet. Should be.",
    ].join("\n"),
  },
  {
    id: "rfc-shared-vaults",
    title: "RFC — shared vaults (sketch)",
    area: AREA.product,
    offset: -18,
    time: "20:00",
    tags: [TAGS.rfc, TAGS.localFirst, TAGS.fundraise],
    body: [
      "**Status:** sketch, not scheduled · **Author:** me",
      "",
      "Written because [[Halyard passed — postmortem]] deserved a real answer rather",
      "than a reframe. This is what the second act looks like if it exists.",
      "",
      "## The shape",
      "",
      "Not real-time multiplayer. A shared vault is a folder two to six people can",
      "each hold a full copy of, synced through a transport they already trust —",
      "a git remote, a shared drive, whatever. No server of record.",
      "",
      "## What that buys",
      "",
      "- Every participant keeps a complete, independently useful copy",
      "- No Woodshed-operated backend, so the privacy claim survives intact",
      "- Works today, badly, if you point two installs at the same Dropbox folder —",
      "  which several users already do",
      "",
      "## What it costs",
      "",
      "Conflicts become visible and frequent instead of rare. [[Adeola Bakare]] is",
      "clear that pretending otherwise is the mistake: no CRDT story for arbitrary",
      "Markdown that does not either lose intent or produce unreadable files.",
      "",
      "So the design is last-write-wins with *every* superseded version kept as a",
      "visible revision, and a real conflict UI. Honest, unglamorous, buildable.",
      "",
      "## Why it is not scheduled",
      "",
      "Because single-player is not finished, and shipping a mediocre collaboration",
      "story to chase a market objection is how this product loses what makes it",
      "worth buying.",
    ].join("\n"),
  },

  // ── Positioning and writing ───────────────────────────────────────────────
  {
    id: "file-over-app",
    title: "File over app",
    area: AREA.growth,
    offset: -58,
    time: "07:15",
    tags: [TAGS.essay, TAGS.localFirst, TAGS.positioning],
    favorite: true,
    body: [
      "The premise is one question: if your tools vanished tomorrow, would your files",
      "survive?",
      "",
      "For most of what people use, the answer is no. There is an export button, and",
      "the export produces something technically complete and practically dead — a",
      "JSON dump, a zip of HTML, a proprietary archive that one program in the world",
      "can read and that program is the one you are leaving.",
      "",
      "Markdown is the answer, not because it is elegant but because it is boring.",
      "Plain text with light structure. Readable in any editor, on any operating",
      "system, in thirty years. The format has no owner, which means it has no",
      "roadmap, which means it cannot be taken away.",
      "",
      "This is the foundation of Woodshed. Every record is a `.md` file. Tags are",
      "inline. Links are wikilinks. The app is a lens, not a cage.",
      "",
      "The cost of this is real and worth naming: you give up the schema flexibility",
      "a database gives you, and every feature has to be expressible as files a",
      "person could read. That is a genuine constraint on what can be built.",
      "",
      "It is also the only promise in this category that cannot be quietly revoked",
      "in a future release.",
    ].join("\n"),
  },
  {
    id: "premium-tool-buyer",
    title: "The premium-tool buyer",
    area: AREA.growth,
    offset: -44,
    time: "09:00",
    tags: [TAGS.positioning],
    body: [
      "ICP working note.",
      "",
      "The premium-tool buyer:",
      "",
      "- Pays for the good version of everything — editor, terminal, task manager",
      "- Treats tools as infrastructure, not novelty",
      "- Optimizes for keyboard speed, density, and trust",
      "- Reads the changelog",
      "- Has been burned by a shutdown and remembers it",
      "",
      "They are not price sensitive and they are ruthlessly quality sensitive.",
      "[[Marcus Bell]] put it best: it is not an expense, it is the chair you sit in",
      "for nine hours.",
      "",
      "The corollary matters more than the profile. This buyer churns when the",
      "product starts feeling *generic* — not when it is missing a feature. Every",
      "roadmap decision that makes us more like everything else is a churn event for",
      "the only customer who was ever going to pay full price.",
    ].join("\n"),
  },
  {
    id: "writing-is-thinking",
    title: "Writing is thinking, not typing",
    area: AREA.growth,
    offset: -41,
    time: "06:50",
    tags: [TAGS.essay],
    body: [
      "Writing is not the output of thinking. It is the thinking. Putting words in",
      "sequence forces you to discover which of your ideas were actually one idea and",
      "which were three, and which were nothing.",
      "",
      "This is why the best engineers write well. Not because writing is a separate",
      "skill they happen to have, but because clear writing is clear thinking made",
      "inspectable by someone else.",
      "",
      "It is also the argument for why a knowledge tool should be uncomfortable to",
      "use as a dumping ground and comfortable to use as a place to reason. Those are",
      "different products.",
    ].join("\n"),
  },
  {
    id: "against-the-empty-vault",
    title: "Against the empty vault",
    area: AREA.product,
    offset: -11,
    time: "22:15",
    tags: [TAGS.positioning, TAGS.essay],
    body: [
      "An empty vault is a chore disguised as a possibility.",
      "",
      "We tell ourselves a blank canvas is generous — the user can do anything. What",
      "the user experiences is an obligation: now you must think of what goes here,",
      "and structure it, and maintain it, forever, alone.",
      "",
      "Both the retention data and [[Iris Chen]]'s forum observations point the same",
      "way from opposite directions. Users who arrive with existing material stay.",
      "Users who start empty leave.",
      "",
      "The fix is not a template gallery. Templates are someone else's structure,",
      "which is its own kind of chore. The fix is import: bring what you already have",
      "and let the structure be the one you already use.",
      "",
      "That is [[RFC — onboarding starts with import]].",
    ].join("\n"),
  },
  {
    id: "what-local-first-actually-means",
    title: "What \"local-first\" actually means (and does not)",
    area: AREA.product,
    offset: -36,
    time: "17:40",
    tags: [TAGS.localFirst, TAGS.positioning],
    body: [
      "The term has been diluted to the point of uselessness. Almost every tool now",
      "claims it, and for most of them it means \"we have a local cache\".",
      "",
      "A test that separates them: **delete every piece of application state that is",
      "not the user's documents. What is lost?**",
      "",
      "For a tool with a local cache, everything is lost — the cache was a copy, the",
      "real database was elsewhere, and without it the copy is inert.",
      "",
      "For Woodshed the answer is: a search index and a calendar cache, both of which",
      "rebuild from the files in seconds. Nothing the user wrote is in them.",
      "",
      "That is the whole distinction and it is worth being pedantic about, because it",
      "is the only version of the claim that survives the company disappearing.",
      "",
      "Related: [[File over app]], [[RFC — shared vaults (sketch)]].",
    ].join("\n"),
  },
  {
    id: "security-model-summary",
    title: "When does data leave the machine?",
    area: AREA.product,
    offset: -27,
    time: "12:00",
    tags: [TAGS.dd, TAGS.localFirst],
    favorite: true,
    body: [
      "Written for [[Jonas Klein]]'s security review, but it should have existed",
      "anyway. This is the enumerable list, not the marketing claim.",
      "",
      "## Network activity, exhaustively",
      "",
      "1. **Mail** — IMAP/SMTP to the configured provider, only for accounts the user",
      "   added, only on sync or send.",
      "2. **Calendar** — HTTPS GET of a user-supplied read-only iCal URL, on sync.",
      "3. **Saved links** — HTTPS fetch of a URL the user explicitly saved, once, with",
      "   time, redirect, address and size limits.",
      "4. **Remote images in HTML mail** — fetched through a bounded local cache.",
      "   Sender HTML never fetches anything directly.",
      "5. **Agent** — requests to the endpoint the user configured, only after an",
      "   explicit send.",
      "",
      "## What does not happen",
      "",
      "No account system. No telemetry. No crash reporting. No Woodshed-operated",
      "backend of any kind. There is no server for vault contents to be sent to,",
      "which is a stronger guarantee than a policy promising they will not be.",
      "",
      "## Where credentials live",
      "",
      "OS credential store. Never the vault, never `config.json`, never logs.",
    ].join("\n"),
  },

  // ── Operating notes ───────────────────────────────────────────────────────
  {
    id: "runway-math",
    title: "Runway math, honestly",
    area: AREA.fundraise,
    offset: -31,
    time: "19:30",
    tags: [TAGS.fundraise],
    body: [
      "[[Alex Rivera]] asked for the real number rather than the encouraging one.",
      "Fair, and I did not have it to hand, which was embarrassing.",
      "",
      "Current burn is four people, one part-time. At today's rate we have about",
      "seven months without the round.",
      "",
      `With ${RAISE.target} closed: eighteen months at a burn that includes two`,
      "engineering hires and [[Casey Kim]] going full-time.",
      "",
      `${RAISE.committed} is committed today — [[Ana Ferreira]], [[Ben Whitfield]],`,
      "[[Nadia Haddad]]. The round is real whether or not Northwind leads; a lead",
      "changes the terms and the timeline, not the survival question.",
      "",
      "Told Alex the seven-month number directly. Correct call — a founding engineer",
      "who finds out later that the number was worse than described never fully",
      "believes the next one.",
    ].join("\n"),
  },
  {
    id: "hiring-plan",
    title: "Hiring plan (post-close)",
    area: AREA.growth,
    offset: -15,
    time: "13:50",
    tags: [TAGS.hiring],
    body: [
      "Not engaging [[Grace Lin]] until the round closes. Starting a search that",
      "cannot be funded wastes candidates' time and burns the recruiter relationship.",
      "",
      "## First two hires",
      "",
      "1. **Systems engineer, Rust.** Owns sync and the write path alongside",
      "   [[Alex Rivera]]. The shared-vaults work is not startable without this",
      "   person.",
      "2. **Product engineer, TypeScript.** Owns the surfaces. Half the backlog is UI",
      "   work that [[Sam Chen]] is currently absorbing on top of leading.",
      "",
      "## Not hiring",
      "",
      "No growth hire, no sales hire, no head of anything. At four people the",
      "distribution strategy is writing and word of mouth, and both of those are",
      "mine to do.",
      "",
      "Grace has two Rust candidates queued. Do not contact them yet.",
    ].join("\n"),
  },
  {
    id: "weekly-update-template",
    title: "Investor update — format",
    area: AREA.fundraise,
    offset: -50,
    time: "08:00",
    tags: [TAGS.fundraise],
    body: [
      "Monthly, short, same shape every time. Sent to committed investors and the",
      "two firms in active diligence.",
      "",
      "1. **Number** — WAU, retention, MRR. Same three, every month, no swapping in",
      "   whichever looks best.",
      "2. **Shipped** — what actually landed, linked.",
      "3. **Learned** — one thing that changed my mind.",
      "4. **Ask** — one specific thing, or explicitly nothing.",
      "",
      "The discipline is in point 1. The temptation every month is to lead with the",
      "metric that moved. Investors notice the swap immediately and it costs more",
      "credibility than a flat month ever would.",
    ].join("\n"),
  },
  {
    id: "demo-script",
    title: "Demo script — what to actually show",
    area: AREA.fundraise,
    offset: -3,
    time: "16:20",
    tags: [TAGS.fundraise, TAGS.positioning],
    favorite: true,
    body: [
      "No slides. Open the app, use it as it is used.",
      "",
      "## Sequence",
      "",
      "1. **Open on today.** Calendar, tasks, and the journal in one view. Do not",
      "   explain it — let it be obvious.",
      "2. **Follow a wikilink** from today's journal to a person, then show their",
      "   backlinks: every meeting, task and mention in one place. This is the moment",
      "   that lands. [[Sofia Duarte]] described it unprompted as the reason she looks",
      "   competent in 1:1s.",
      "3. **Search something.** Fast, across every surface.",
      "4. **Show the folder in Finder.** Same records, plain Markdown, readable",
      "   without the app. This is the whole pitch and it takes eight seconds.",
      "5. **Open one file in a text editor.** Let them read the frontmatter.",
      "",
      "## Do not",
      "",
      "- Do not open Settings",
      "- Do not explain the architecture unless asked",
      "- Do not apologise for anything unfinished — note it and move on",
      "",
      "If there is time, the Databases surface. If there is not, skip it; it is the",
      "least differentiated part of the product.",
    ].join("\n"),
  },
  {
    id: "questions-i-cannot-answer",
    title: "Questions I still cannot answer well",
    area: AREA.fundraise,
    offset: -5,
    time: "23:00",
    tags: [TAGS.fundraise],
    body: [
      "Keeping this honest list so I stop being surprised in meetings.",
      "",
      "1. **What is the second act?** [[RFC — shared vaults (sketch)]] is the best",
      "   answer I have and it is a sketch, not a plan. Say that plainly rather than",
      "   overselling it.",
      "2. **Why does Obsidian not just do this?** They could. The honest answer is",
      "   that first-party calendar and mail requires being a native app with real",
      "   platform integration, and a plugin ecosystem is a strategic reason not to",
      "   go there. That is a real moat and a narrow one.",
      "3. **What is the wedge that is not \"nice tool\"?** Still working on this.",
      "   The closest I have is that we are the only place a person's calendar, mail",
      "   and notes share one link graph without a vendor in the middle.",
      "4. **Pricing.** $20/month is a guess anchored on comparable tools, not on any",
      "   willingness-to-pay work. Nobody has pushed hard on it yet. Someone will.",
      "",
      "Rule: when one of these comes up, say \"that is the open question\" and give the",
      "best current thinking. Do not improvise confidence.",
    ].join("\n"),
  },
  {
    id: "design-review-notes",
    title: "Design review — Databases board view",
    area: AREA.product,
    offset: -10,
    time: "11:45",
    tags: [TAGS.rfc],
    body: [
      "Present: [[Sam Chen]], [[Casey Kim]], [[Morgan Diaz]].",
      "",
      "Reviewing the grouped board view [[Hana Sato]] asked for.",
      "",
      "## Agreed",
      "",
      "- Board groups by any select column, drag between groups writes the cell",
      "- Per-group calculation footer, same functions as table views",
      "- Group order follows the column's option order, not alphabetical",
      "",
      "## Rejected",
      "",
      "Cross-row formulas. Sam's argument settled it: a formula cell is a value that",
      "only the app can compute, which means the Markdown file is no longer",
      "self-describing. That is the one line Databases does not cross.",
      "",
      "## Open",
      "",
      "What happens to rows whose group-by cell is empty? Casey wants a visible",
      "\"No value\" column; Morgan wants them hidden. Casey is right — hiding records",
      "is how people lose them.",
    ].join("\n"),
  },
  {
    id: "reading-queue",
    title: "Reading queue",
    area: AREA.personal,
    offset: -6,
    time: "21:40",
    tags: [],
    body: [
      "Things to get to when the round is done.",
      "",
      "- The Ink & Switch essays properly, not skimmed for quotable lines",
      "- Two papers [[Adeola Bakare]] sent on operational transforms, which I have",
      "  been avoiding because they will probably complicate the shared-vaults sketch",
      "- Something that is not about software",
      "",
      "Noting the third one seriously. Eight weeks of raising has made everything I",
      "read instrumental and it shows in the writing.",
    ].join("\n"),
  },
  {
    id: "week-in-review",
    title: "Week in review",
    area: AREA.personal,
    offset: -2,
    time: "18:00",
    tags: [],
    body: [
      "Short one. Demo day is Monday.",
      "",
      "**Good:** Foundry Line reference call went well — [[Ravi Menon]] apparently",
      "spent twenty minutes on the iCloud bug and how it was handled, which is the",
      "best possible reference. Index warmup shipped.",
      "",
      "**Bad:** the YC application is still not cut down and it is due Friday.",
      "Slept badly all week.",
      "",
      "**Next week:** Northwind partner meeting Thursday. SPC dinner Monday. Do not",
      "schedule anything else.",
    ].join("\n"),
  },
];

export function buildNotebook(w: VaultWriter, cal: Calendar): void {
  for (const note of NOTES) {
    writeNote(w, {
      id: note.id,
      title: note.title,
      area: note.area,
      created: cal.atNaive(note.offset, note.time),
      tags: note.tags,
      favorite: note.favorite,
      body: note.body,
    });
  }
}
