import type { Calendar } from "../dates";
import { writeResource, type VaultWriter } from "../emit";
import { TAGS } from "./narrative";

interface ResourceSeed {
  id: string;
  title: string;
  url: string;
  source: string;
  author?: string;
  offset: number;
  time: string;
  tags: string[];
  highlights?: string[];
  favorite?: boolean;
  body: string;
}

// Real URLs here are public, widely-linked documents (essays, project docs,
// specifications). Everything else — anything resembling a private post, an
// investor memo, a competitor's internal writing — is fictional and uses the
// reserved `.example` TLD.
const RESOURCES: ResourceSeed[] = [
  {
    id: "local-first-software",
    title: "Local-first software: you own your data, in spite of the cloud",
    url: "https://www.inkandswitch.com/local-first/",
    source: "inkandswitch.com",
    author: "Ink & Switch",
    offset: -61,
    time: "09:15",
    tags: [TAGS.localFirst, "philosophy"],
    favorite: true,
    body: [
      "The foundational text. The seven ideals are a genuinely useful checklist —",
      "we fail two of them (real-time collaboration, seamless multi-device) and I",
      "would rather name that than pretend otherwise.",
      "",
      "The idea I keep coming back to: the copy on your device shouldn't be a cache",
      "of the server's data, it should be the other way round. That inversion is the",
      "whole architecture in one sentence and I have never improved on it.",
    ].join("\n"),
  },
  {
    id: "file-over-app-essay",
    title: "File over app",
    url: "https://stephango.com/file-over-app",
    source: "stephango.com",
    author: "Steph Ango",
    offset: -59,
    time: "14:30",
    tags: [TAGS.localFirst, "philosophy"],
    favorite: true,
    highlights: [
      "If you want your writing to still be readable on a computer from the 2060s, it's important that your notes can be read on a computer from the 1960s.",
    ],
    body: [
      "The post that named the principle. Worth re-reading every product cycle,",
      "particularly before any decision that would put data somewhere only our app",
      "can read.",
      "",
      "Fed directly into [[File over app]].",
    ].join("\n"),
  },
  {
    id: "sqlite-fts5",
    title: "SQLite FTS5 extension",
    url: "https://www.sqlite.org/fts5.html",
    source: "sqlite.org",
    offset: -53,
    time: "16:00",
    tags: ["engineering", "search"],
    highlights: [
      "FTS5 is an SQLite virtual table module that provides full-text search functionality to database applications.",
    ],
    body: [
      "Reference for the search index. The prefix-index section is the part that",
      "matters for as-you-type search — worth re-reading before touching the schema.",
      "",
      "Relevant to [[RFC — warm the search index at launch]].",
    ].join("\n"),
  },
  {
    id: "tauri-security",
    title: "Tauri security model",
    url: "https://v2.tauri.app/security/",
    source: "tauri.app",
    offset: -49,
    time: "11:20",
    tags: ["engineering", TAGS.dd],
    body: [
      "The capability model — frontend treated as untrusted, permissions granted",
      "explicitly per window — is why our webview has no general filesystem access.",
      "",
      "Cited directly in [[When does data leave the machine?]].",
    ].join("\n"),
  },
  {
    id: "markdown-syntax",
    title: "Markdown syntax documentation",
    url: "https://daringfireball.net/projects/markdown/syntax",
    source: "daringfireball.net",
    author: "John Gruber",
    offset: -57,
    time: "08:45",
    tags: [TAGS.localFirst],
    highlights: [
      "The overriding design goal for Markdown's formatting syntax is to make it as readable as possible.",
    ],
    body: [
      "The original. Kept for the design-goal quote, which is the actual argument",
      "for why the format outlives its tools: it was designed to be read by humans",
      "first and parsed second.",
    ].join("\n"),
  },
  {
    id: "upwelling-collaboration",
    title: "Upwelling: combining real-time collaboration with version control",
    url: "https://www.inkandswitch.com/upwelling/",
    source: "inkandswitch.com",
    author: "Ink & Switch",
    offset: -20,
    time: "20:30",
    tags: [TAGS.localFirst, TAGS.rfc],
    body: [
      "Sent by [[Adeola Bakare]] after the shared-vaults conversation.",
      "",
      "The tension it works on: writers want to draft privately before sharing, and",
      "real-time collaboration makes every keystroke public.",
      "",
      "The private-draft-then-publish model is closer to what a shared vault should",
      "feel like than real-time multiplayer is. Directly relevant to",
      "[[RFC — shared vaults (sketch)]].",
    ].join("\n"),
  },
  {
    id: "crdt-are-not-enough",
    title: "CRDTs solve the wrong half of the problem",
    url: "https://notes.adeola.example/crdt-wrong-half",
    source: "notes.adeola.example",
    author: "Adeola Bakare",
    offset: -22,
    time: "19:00",
    tags: [TAGS.localFirst, TAGS.rfc],
    highlights: [
      "A CRDT guarantees the documents converge. It does not guarantee the result means anything.",
    ],
    body: [
      "[[Adeola Bakare]]'s own writing on why automatic merges of prose produce",
      "syntactically valid, semantically incoherent documents.",
      "",
      "This is the argument that talked me out of promising conflict-free editing in",
      "[[Seed investor memo]].",
    ].join("\n"),
  },
  {
    id: "seed-round-mechanics",
    title: "How post-money SAFEs actually dilute you",
    url: "https://writing.foundryline.example/safe-dilution",
    source: "writing.foundryline.example",
    author: "Mei Watanabe",
    offset: -46,
    time: "07:30",
    tags: [TAGS.fundraise],
    highlights: [
      "Stacking post-money SAFEs at different caps does not dilute linearly, and founders routinely discover this at the priced round.",
    ],
    body: [
      "Sent by [[Mei Watanabe]] before the Foundry Line diligence call. Read it",
      "before agreeing to any second cap.",
      "",
      "Ran our own numbers against this — the current stack is clean because every",
      `commit is at the same cap. Keep it that way.`,
    ].join("\n"),
  },
  {
    id: "what-partners-actually-read",
    title: "What a partner actually reads in your memo",
    url: "https://writing.northwind.example/memo-reading",
    source: "writing.northwind.example",
    author: "Priya Raman",
    offset: -51,
    time: "06:40",
    tags: [TAGS.fundraise, TAGS.positioning],
    highlights: [
      "I read the traction section first, then I go looking for the paragraph where you admit what is not working. If there isn't one, I stop reading.",
    ],
    body: [
      "[[Priya Raman]]'s own writing, found before the first call. The highlight is",
      "why [[Seed investor memo]] has an explicit objection section — it is not",
      "candour for its own sake, it is what this reader is looking for.",
    ].join("\n"),
  },
  {
    id: "the-shutdown-post",
    title: "We are sunsetting Fernweave on March 31",
    url: "https://blog.fernweave.example/sunset",
    source: "blog.fernweave.example",
    offset: -43,
    time: "10:00",
    tags: [TAGS.positioning, TAGS.localFirst],
    highlights: [
      "You will be able to export your data in a JSON archive until the shutdown date.",
      "We are proud of what we built and grateful to our community.",
    ],
    body: [
      "Keeping this as the canonical example of the thing the product exists to",
      "prevent. Note the export format: a JSON archive, which is technically an",
      "export and practically a tombstone.",
      "",
      "Nobody's notes survive this. That is the market.",
    ].join("\n"),
  },
  {
    id: "keyboard-first-interfaces",
    title: "Keyboard-first interfaces are an accessibility feature",
    url: "https://essays.tinderbox.example/keyboard-first",
    source: "essays.tinderbox.example",
    author: "Marcus Bell",
    offset: -25,
    time: "15:15",
    tags: [TAGS.positioning],
    highlights: [
      "Every action that requires the mouse is an action some people cannot perform quickly, and everyone performs slowly.",
    ],
    body: [
      "[[Marcus Bell]] wrote this after complaining to me about the command palette.",
      "",
      "The reframe is correct and I had been thinking about keyboard completeness as",
      "a power-user preference rather than an access question.",
    ].join("\n"),
  },
  {
    id: "pricing-anchor-research",
    title: "What people actually pay for desktop productivity tools",
    url: "https://research.meridian.example/desktop-pricing",
    source: "research.meridian.example",
    offset: -17,
    time: "12:30",
    tags: [TAGS.fundraise, TAGS.positioning],
    highlights: [
      "Willingness to pay for a daily-use desktop tool clusters at $8-12/month and again at $18-25/month, with almost nothing between.",
    ],
    body: [
      "The bimodal distribution is interesting and slightly reassuring — $20/month",
      "sits in the upper cluster rather than in the dead zone.",
      "",
      "Still a guess though. See point 4 of [[Questions I still cannot answer well]].",
    ].join("\n"),
  },
  {
    id: "obsidian-plugin-ecosystem",
    title: "The strategic cost of a plugin ecosystem",
    url: "https://analysis.ostrich.example/plugin-lock-in",
    source: "analysis.ostrich.example",
    offset: -32,
    time: "17:00",
    tags: [TAGS.positioning],
    highlights: [
      "Once third parties depend on your internals, your roadmap belongs to them.",
    ],
    body: [
      "Relevant to the competitors question. A mature plugin ecosystem is a real",
      "moat against newcomers and a real constraint on first-party features — which",
      "is the narrow gap this product lives in.",
      "",
      "Feeds question 2 of [[Questions I still cannot answer well]].",
    ].join("\n"),
  },
  {
    id: "fsync-considered-harmful",
    title: "Files are hard",
    url: "https://danluu.com/file-consistency/",
    source: "danluu.com",
    author: "Dan Luu",
    offset: -48,
    time: "22:00",
    tags: ["engineering", TAGS.localFirst],
    body: [
      "Read this again after the iCloud data-loss bug. Sobering.",
      "",
      "The survey of what filesystems actually guarantee under crash — as opposed to",
      "what everyone assumes they guarantee — is the part to reread.",
      "",
      "The direct-write fallback in [[RFC — iCloud direct-write fallback]] has a",
      "crash window this article describes precisely. The mitigation — write a",
      "revision first — is still not done.",
    ].join("\n"),
  },
  {
    id: "tanstack-query-docs",
    title: "TanStack Query — query invalidation",
    url: "https://tanstack.com/query/latest/docs/framework/react/guides/query-invalidation",
    source: "tanstack.com",
    offset: -55,
    time: "13:00",
    tags: ["engineering"],
    body: [
      "Reference for the invalidation strategy. Query keys follow vault paths so a",
      "filesystem event can invalidate exactly the affected records rather than",
      "refetching everything.",
    ].join("\n"),
  },
  {
    id: "founder-mode-of-writing",
    title: "Write the update you would want to receive",
    url: "https://letters.ridgeline.example/investor-updates",
    source: "letters.ridgeline.example",
    author: "Ana Ferreira",
    offset: -39,
    time: "09:30",
    tags: [TAGS.fundraise],
    highlights: [
      "The founders I trust most send the same three metrics every month, including the months those metrics are flat.",
    ],
    body: [
      "[[Ana Ferreira]]'s writing on updates. This is where the rule in",
      "[[Investor update — format]] came from — never swap the headline metric for",
      "whichever one moved.",
    ].join("\n"),
  },
  {
    id: "security-questionnaire-template",
    title: "A security questionnaire that does not waste everyone's time",
    url: "https://handbook.ostrich.example/vendor-security",
    source: "handbook.ostrich.example",
    author: "Jonas Klein",
    offset: -28,
    time: "10:45",
    tags: [TAGS.dd],
    highlights: [
      "Ask what leaves the machine and under what trigger. Everything else is downstream of that answer.",
    ],
    body: [
      "[[Jonas Klein]] sent his own template rather than the standard 300-question",
      "spreadsheet, which was generous.",
      "",
      "The framing question is the one [[When does data leave the machine?]] answers.",
    ].join("\n"),
  },
  {
    id: "interviewing-users-properly",
    title: "Stop asking users what they want",
    url: "https://notes.meridian.example/user-interviews",
    source: "notes.meridian.example",
    author: "Sofia Duarte",
    offset: -37,
    time: "08:15",
    tags: [TAGS.userInterview],
    highlights: [
      "Ask what they did last Tuesday. Feature requests are hypotheses about their own behaviour, and people are bad at those.",
    ],
    body: [
      "[[Sofia Duarte]] on interview technique. Changed how I run these — the",
      "backlinks-as-CRM insight in her own interview only surfaced because I asked",
      "what she actually did before a 1:1 rather than what she wanted.",
    ].join("\n"),
  },
  {
    id: "native-app-renaissance",
    title: "The native app renaissance is a trust story",
    url: "https://devtools.almeida.example/native-renaissance",
    source: "devtools.almeida.example",
    author: "Theo Almeida",
    offset: -23,
    time: "07:50",
    tags: [TAGS.positioning],
    highlights: [
      "People are not returning to native apps because Electron got slower. They are returning because a local binary is legible in a way a web app never is.",
    ],
    body: [
      "[[Theo Almeida]]'s piece. He wants to cover the launch and this is a good",
      "signal of the angle he would take — trust rather than performance.",
      "",
      "Time the outreach to the round closing.",
    ].join("\n"),
  },
  {
    id: "yc-application-advice",
    title: "Notes on writing a strong accelerator application",
    url: "https://advice.fischer.example/applications",
    source: "advice.fischer.example",
    author: "Lena Fischer",
    offset: -14,
    time: "18:45",
    tags: [TAGS.fundraise],
    highlights: [
      "Every answer should be falsifiable. Vague answers read as a founder who has not yet been forced to be specific.",
    ],
    body: [
      "[[Lena Fischer]]'s advice, sent unprompted when she heard I was applying.",
      "",
      "Used it to cut the first draft of [[YC W27 application — draft answers]] hard.",
      "The \"why now\" answer still fails this test and needs another pass.",
    ].join("\n"),
  },
  {
    id: "sync-without-server",
    title: "Syncing files without a server of record",
    url: "https://papers.bakare.example/serverless-sync",
    source: "papers.bakare.example",
    author: "Adeola Bakare",
    offset: -30,
    time: "21:20",
    tags: [TAGS.localFirst, TAGS.rfc],
    highlights: [
      "Any transport the participants already trust is a valid sync layer. The hard part was never transport.",
    ],
    body: [
      "Underpins the transport-agnostic part of [[RFC — shared vaults (sketch)]].",
      "",
      "The point that stuck: the hard problem is conflict presentation, not moving",
      "bytes. We keep wanting it to be the other way round because moving bytes is",
      "the part that feels like engineering.",
    ].join("\n"),
  },
  {
    id: "changelog-as-marketing",
    title: "The changelog is the product page",
    url: "https://essays.tinderbox.example/changelog-marketing",
    source: "essays.tinderbox.example",
    author: "Marcus Bell",
    offset: -34,
    time: "11:10",
    tags: [TAGS.positioning],
    highlights: [
      "For the buyer who matters, a well-written changelog is stronger evidence than any landing page.",
    ],
    body: [
      "Matches the ICP profile in [[The premium-tool buyer]] exactly. This buyer",
      "reads the changelog before deciding, which means the changelog deserves real",
      "writing time rather than a bullet list generated from commits.",
    ].join("\n"),
  },
  {
    id: "climbing-training-plan",
    title: "Base fitness for climbers who sit down all day",
    url: "https://training.whitcomb.example/desk-climbers",
    source: "training.whitcomb.example",
    author: "Nora Whitcomb",
    offset: -26,
    time: "20:00",
    tags: [],
    body: [
      "[[Nora Whitcomb]] sent this after I complained about my shoulders.",
      "",
      "Two sessions a week, which is what we already do. The point of the article is",
      "that the sitting is the problem, not the climbing.",
    ].join("\n"),
  },
  {
    id: "deep-work-scheduling",
    title: "Protecting mornings during a fundraise",
    url: "https://advice.fischer.example/fundraise-calendar",
    source: "advice.fischer.example",
    author: "Lena Fischer",
    offset: -45,
    time: "06:30",
    tags: [TAGS.fundraise],
    highlights: [
      "A raise will expand to fill every hour you leave unguarded. Block the mornings before the first call, not after the tenth.",
    ],
    body: [
      "Ignored this for three weeks and then the calendar proved her right.",
      "",
      "Mornings are now blocked before 10:00. Everything investor-facing goes",
      "afternoon. The writing quality difference was immediate.",
    ].join("\n"),
  },
  {
    id: "one-more-thing",
    title: "Against roadmaps",
    url: "https://writing.cartogram.example/against-roadmaps",
    source: "writing.cartogram.example",
    author: "Hana Sato",
    offset: -8,
    time: "14:20",
    tags: [TAGS.positioning],
    highlights: [
      "A public roadmap converts every prioritisation decision into a negotiation with people who do not carry the consequences.",
    ],
    body: [
      "[[Hana Sato]] arguing against the thing she is currently asking me for, which",
      "is why it is worth reading.",
      "",
      "Relevant to the Databases scope fight — every request is reasonable in",
      "isolation and the aggregate is a different product.",
    ].join("\n"),
  },
];

export function buildResources(w: VaultWriter, cal: Calendar): void {
  for (const resource of RESOURCES) {
    writeResource(w, {
      id: resource.id,
      title: resource.title,
      url: resource.url,
      source: resource.source,
      author: resource.author,
      saved: cal.at(resource.offset, resource.time),
      tags: resource.tags,
      highlights: resource.highlights ?? [],
      favorite: resource.favorite,
      body: resource.body,
    });
  }
}
